bounswe/bounswe2019group11

practice-app/README.md
=> initial commit

.gitignore, practice-app/README.md, practice-app/index.js, practice-app/package.json, practice-app/views/layout.pug, practice-app/views/register.pug
This is what we have looked at during the meeting @ Monday, 29.04.19
=> Code to start looking at Express.js

practice-app/.env
Sorry guys. I forgot the .env file in the last pr.
=> Add .env file

practice-app/index.js, practice-app/views/home.pug, practice-app/views/layout.pug
With these changes, we can add links to the navbar as we add new features so that the user can easily navigate between them. 
Also, added a small cards for features.
Here is the SS for the changed homepage
=> add a simple home page layout and navigation bar

practice-app/.env, practice-app/helpers/db.js, practice-app/index.js, practice-app/models/users.js, practice-app/package.json, practice-app/routes/register.js, practice-app/views/register.pug
=> Add register logic with User model

.gitignore, practice-app/index.js, practice-app/package.json
There were two app.listen() method. I did not realized while merging. Now I fixed the problem.
=> .idea/ added to gitignore

practice-app/README.md, practice-app/views/exchange_rate.pug, practice-app/views/home.pug, practice-app/views/layout.pug
updated the exchange rate api with the recent changes
here is the final look for the exchange rate view
=> update view for the exchange rate api

practice-app/.env, practice-app/README.md, practice-app/routes/exchange_rate_api.js, practice-app/views/exchange_rate.pug
Created a new API to calculate the average exchange rate values for a given time interval. Made some changes to frontend as I added a form section for the average calculation.
=> Added average calculation api for exchange rates

practice-app/routes/exchange_rate_api.js, practice-app/views/exchange_rate.pug
added the percentage change feature to our API. it gives the percentage change on a selected currency to another one, from the previous day.
=> added percentage change feature to the exchange rates API

practice-app/routes/stock.js, practice-app/views/home.pug, practice-app/views/layout.pug, practice-app/views/stock.pug
Fix bug in stock indexes front end and also add stock indexes links to home and layout
=> Fix frontend of stock indexes

backend/helpers/errors.js, backend/models/user.js, backend/routes/auth.js, backend/services/auth.js, backend/swagger.json
Login endpoint is implemented. A user can try to login with its email and password. Refer to the swagger documentation for the status codes and their meanings. 
fixes #125
=> implement login endpoint

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/papel/ui/home/HomeViewModel.java, android/app/src/main/java/com/papel/ui/home/data/LoginDataSource.java, android/app/src/main/java/com/papel/ui/home/data/LoginRepository.java, android/app/src/main/java/com/papel/ui/home/data/Result.java, android/app/src/main/java/com/papel/ui/home/data/model/LoggedInUser.java, android/app/src/main/java/com/papel/ui/home/ui/login/LoggedInUserView.java, android/app/src/main/java/com/papel/ui/home/ui/login/LoginActivity.java, android/app/src/main/java/com/papel/ui/home/ui/login/LoginFormState.java, android/app/src/main/java/com/papel/ui/home/ui/login/LoginResult.java, android/app/src/main/java/com/papel/ui/home/ui/login/LoginViewModel.java, android/app/src/main/java/com/papel/ui/home/ui/login/LoginViewModelFactory.java, android/app/src/main/res/layout/activity_login.xml, android/app/src/main/res/values/strings.xml
Login page is added. Will be modified.
=> Added login page. 

android/app/src/main/java/com/papel/ui/home/ui/login/LoginActivity.java, android/app/src/main/res/layout/activity_login.xml, android/app/src/main/res/values/strings.xml
Added login-signup page in single page functionality.
=> Added login-signup page in single page functionality.

android/app/build.gradle, android/app/src/main/java/com/papel/ui/home/ui/login/LoginActivity.java, android/app/src/main/res/layout/activity_login.xml, android/build.gradle
I've added a dialog box on **"Sign Up"** click and re-arranged **Text View**s. 
Login button now takes you to homepage.
=> Rearranged login page, added signup dialog box.

backend/helpers/errors.js, backend/models/user.js, backend/routes/auth.js, backend/services/auth.js, backend/swagger.json
Location info is added to the user model with the latitude and longitude fields. Also, swagger documentation is updated.
fixes #146
=> add location info to the user model

backend/helpers/auth.js, backend/helpers/errors.js, backend/models/user.js, backend/package.json, backend/routes/auth.js, backend/services/auth.js
iban and id number is validated in the user model and any error is returned to the caller if these fields are present.
for the iban validation, `iban` module is used.
fixes #142
=> validate iban and id number during model verification

frontend/papel-frontend/package-lock.json, frontend/papel-frontend/package.json, frontend/papel-frontend/src/App.js, frontend/papel-frontend/src/Article/Articles.js, frontend/papel-frontend/src/Register/Register.js
Added react-bootstrap
Registeration uses modals for email validation redirect
Articles page added
=> Modal for registeration and articles page

backend/routes/auth.js, backend/services/auth.js, backend/swagger.json
Implemented email verification endpoint with its swagger documentation.
fixes #124
=> implement email verification resend endpoint

backend/app.js, backend/helpers/auth.js, backend/helpers/errors.js, backend/middlewares/attachUser.js, backend/middlewares/isAuthenticated.js, backend/models/article.js, backend/models/event.js, backend/models/lostPasswordToken.js, backend/models/stock.js, backend/models/tradingEquipment.js, backend/models/user.js, backend/routes/event.js, backend/routes/profile.js, backend/routes/stock.js, backend/services/auth.js, backend/services/email.js, backend/services/event.js, backend/services/profile.js, backend/services/stock.js, backend/swagger.json
=> implement lost password endpoint

backend/app.js, backend/routes/user.js, backend/services/user.js, backend/swagger.json
Simple user endpoints that return all the users and user with the given id is implemented.
fixes #170
=> implement get user endpoints

backend/helpers/errors.js, backend/middlewares/isAuthenticated.js, backend/models/article.js, backend/routes/article.js, backend/services/article.js, backend/swagger.json
and implement authentication check for adding articles
=> fix article related errors

backend/routes/article.js, backend/services/article.js, backend/services/auth.js
minor fixes for the first milestone
=> Milestone1

android/app/src/main/java/com/papel/data/Event.java
=> Changed date format of event.

backend/helpers/database.js, backend/helpers/errors.js, backend/models/article.js, backend/models/articleComment.js, backend/routes/article.js, backend/services/article.js, backend/swagger.json
=> implement comments endpoint for articles

backend/routes/article.js, backend/services/article.js, backend/swagger.json
The authentication check on edit comment endpoint was missing. I added that.
Thanks to @aysusayin for spotting that.
=> add missing authentication check on edit comment

backend/helpers/errors.js, backend/models/article.js, backend/models/articleVote.js, backend/routes/article.js, backend/services/article.js, backend/swagger.json
Article voting endpoints are implemented. Authenticated users now can up vote or down vote articles (also clear their votes). Vote counts are returned with all article endpoints in the `voteCount` field.
=> add up vote, down vote, clear vote endpoints

android/app/src/main/java/com/papel/ui/login/LoginActivity.java, android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java, android/app/src/main/res/layout/activity_login.xml, android/app/src/main/res/layout/activity_profile.xml, android/app/src/main/res/values/strings.xml
Added design of buttons. Should implement backend connection of google sign in. Should implement public-private functionality.
=> Google Sign in button added. Public-private profile button added.

android/app/build.gradle, android/app/google-services.json, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/FirebaseNotificationService.java, android/app/src/main/java/com/papel/ui/login/LoginActivity.java, android/build.gradle
Adding Firebase project to Android application to resolve the #210.I simply registered the app to Firebase console, added notification library and created messaging service.
=> Add Firebase to project and receive notifications

android/app/build.gradle, android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java, android/build.gradle
Solves the #217 
I used [this](https://github.com/abumoallim/Android-Multi-Select-Dialog) library to implement the search functionality.
=> Add search android

backend/helpers/auth.js, backend/middlewares/isAuthenticated.js, backend/routes/article.js, backend/services/article.js, backend/swagger.json
Formerly, backend wasn't sending the vote of the user on articles. Now, the response contains `userVote` field, which is equal to 0 if the user didn't vote, 1 if up voted the article and -1 if down voted the article.
cc @aysusayin
=> return user vote on article endpoints

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/ui/login/LoginActivity.java
=> Add selecting Google account in login

android/app/src/main/java/com/papel/data/Article.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/article_header.xml
This solves the problem mention in the issue #208's comment.
I added user vote to article page so when user clicks on the article, she can see the vote that she have given on that article and change her previous vote.
=> Added user vote to article page

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/data/Article.java, android/app/src/main/java/com/papel/data/Comment.java, android/app/src/main/java/com/papel/ui/articles/ArticlesFragment.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java, android/app/src/main/java/com/papel/ui/profile/ProfileListViewAdapter.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageAdapter.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/activity_profile.xml, android/app/src/main/res/layout/fragment_profile_subpage.xml, android/app/src/main/res/layout/portfolio_row.xml, android/app/src/main/res/layout/profile_row.xml
I implemented basic layout for the profile page. Right now, follow button is not working since we don't have the API. 
Next features can be:
=> Android profile

android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java, android/app/src/main/res/layout/activity_trading_equipment_detail.xml, android/app/src/main/res/layout/trading_equipment_header.xml, android/app/src/main/res/values/strings.xml
Added prediction and comment section to trading equipment page. Right now it is only the design, the functionalities are not implemented.
Issues #246 and #209.
=> Changed trading equipment detail page design 

android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/profile/ProfileListViewAdapter.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java, android/app/src/main/res/layout/profile_row.xml, android/app/src/main/res/values/strings.xml
From the Pull Request #241 , following features are implemented. 
-  Open article page when the user clicks the article from the list
-  Open portfolio page when the user clicks the portfolio from the list
-  Show proper message when there is no article or portfolio
-  Do not show the whole body of the article in the list
-  Show date in the article
=> Profile articles & portfolios implementation

android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java, android/app/src/main/java/com/papel/ui/portfolio/PortfolioFragment.java, android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageAdapter.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java
=> Fix the bug where user sees the portfolio add button in others' portfolios.

frontend/papel-frontend/src/App.js, frontend/papel-frontend/src/Article/Article.js, frontend/papel-frontend/src/Article/ArticlePreview.js, frontend/papel-frontend/src/Profile/Portfolio.js, frontend/papel-frontend/src/Profile/Profile.js, frontend/papel-frontend/src/Profile/ProfileCard.js, frontend/papel-frontend/src/Profile/UserProfile.css, frontend/papel-frontend/src/Profile/UserProfile.js, frontend/papel-frontend/src/Trading/TradingEquipment.js, frontend/papel-frontend/src/helpers/request.js
- Can view articles and portfolios of other users
- Can delete stocks from your own portfolios
- Some helper functions to abstract the requests
=> Profile Pages for Other Users Added and Small Changes&Fixes

frontend/papel-frontend/src/App.css, frontend/papel-frontend/src/App.js, frontend/papel-frontend/src/Article/Article.js, frontend/papel-frontend/src/Article/CommentPreview.js, frontend/papel-frontend/src/Home/Home.js, frontend/papel-frontend/src/Profile/Portfolio.js, frontend/papel-frontend/src/helpers/geocoder.js, frontend/papel-frontend/src/helpers/request.js
=> Home page and comments update

android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsFragment.java
To solve issue #263. I added an extra condition in the if statement where the menu is inflated.
=> Check user and author id matches when an article comment is pressed

backend/jobs/jobs.js, backend/package.json
Response from the Alpha Vantage is shown correctly in case of an error and cron script is removed from the package.json since starting it this way was not causing it to run  in background
=> fix cron job scripts

backend/app.js, backend/helpers/errors.js, backend/models/investments.js, backend/routes/investments.js, backend/routes/profile.js, backend/services/investments.js
Implementation of investments section's service routes and model
=> Investments backend

backend/helpers/errors.js, backend/models/currencyComment.js, backend/models/event.js, backend/models/stockComment.js, backend/routes/currency.js, backend/routes/stock.js, backend/services/currency.js, backend/services/event.js, backend/services/stock.js
Comments on events remove and post comment endpoint, delete comment endpoint, edit comment endpoint implemented on Stock and Currency
=> Comments on Stock and Currency

backend/routes/currency.js, backend/services/currency.js
Comments on currency was not working. Reverted it for now
=> revert comments on currency

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/data/Currency.java, android/app/src/main/java/com/papel/data/Stock.java, android/app/src/main/java/com/papel/data/TradingEquipment.java, android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentListViewAdapter.java, android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsFragment.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/activity_trading_equipment_detail.xml
=> Add currency

backend/helpers/errors.js, backend/models/portfolio.js, backend/routes/portfolio.js, backend/services/portfolio.js
In addition to stocks; trading equipments and currencies can now be added to portfolios
=> Added trading equipments and currencies to the portfolio

android/app/src/main/java/com/papel/data/Comment.java, android/app/src/main/java/com/papel/data/Currency.java, android/app/src/main/java/com/papel/data/Stock.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentListViewAdapter.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/trading_equipment_header.xml, android/app/src/main/res/layout/trading_equipment_row.xml, android/app/src/main/res/values/strings.xml
Right now only currency supports comments. Add comment, delete comment and edit comment functionalities are implemented. 
Also added a textview to trading equipment row layout to indicate the type of the trading equipment.
=> Added comments to trading equipments

android/app/src/main/java/com/papel/data/Currency.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/trading_equipment_header.xml, android/app/src/main/res/values/strings.xml
Implemented prediction part for trading equipment. Right now the functionality only works for currency.
Partly solves #209
=> Prediction for trading equipment is implemented.

android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java, android/app/src/main/res/layout/article_header.xml, android/app/src/main/res/layout/trading_equipment_header.xml, android/app/src/main/res/values/strings.xml
If there are no comments on the content, "no comments" text is shown.
=> "No comment" text added

android/app/src/main/java/com/papel/data/Currency.java, android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
Now, users can add and delete currencies from portfolios.
=> Add currency to portfolio

android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java, android/app/src/main/res/layout/activity_profile.xml
Hide profile button during the request and show proper follow button according to user's privacy setting.
=> Profile follow button fix

backend/app.js, backend/helpers/errors.js, backend/middlewares/isTrader.js, backend/models/user.js, backend/routes/money.js, backend/services/money.js, backend/swagger.json
Implemented endpoints to view, deposit and withdraw money. 
To perform any of these, user must be authenticated and trader. 
fixes #299
=> Implement money related endpoints

backend/routes/article.js, backend/services/article.js, backend/swagger.json, frontend/papel-frontend/src/App.js, frontend/papel-frontend/src/Article/AddArticle.js, frontend/papel-frontend/src/Article/Article.js, frontend/papel-frontend/src/Article/ArticlePreview.js, frontend/papel-frontend/src/Article/Articles.js, frontend/papel-frontend/src/Currency/Currencies.js, frontend/papel-frontend/src/Currency/CurrencyTable.js, frontend/papel-frontend/src/Currency/CurrencyView.js, frontend/papel-frontend/src/EconEvent/EconEvent.js, frontend/papel-frontend/src/EconEvent/EconEvents.js, frontend/papel-frontend/src/Home/Home.js, frontend/papel-frontend/src/Login/Login.js, frontend/papel-frontend/src/Profile/Portfolio.js, frontend/papel-frontend/src/Profile/Profile.js, frontend/papel-frontend/src/Profile/UserProfile.js, frontend/papel-frontend/src/Register/Register.js, frontend/papel-frontend/src/Trading/TradingEquipment.js, frontend/papel-frontend/src/config.js
modify src/config.js according to which api url to communicate
=> Frontend config

android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java
Portfolios were not downloading properly. This bug has been fixed.
=> A small bug-fix with the profile activity.

android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentListViewAdapter.java
=> Changed the trading equipment title to represent the parity

android/app/build.gradle, android/app/src/main/java/com/papel/data/Article.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/article_header.xml
Solves #305 
I added Glide library to load images.
=> Add image to article

backend/routes/stock.js, backend/services/stock.js, backend/swagger.json
Fixed the stock comments and added the swagger documentation.
fixes #314
=> fix stock comments and add swagger documentation

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/ui/money/MoneyFragment.java, android/app/src/main/res/layout/fragment_money.xml, android/app/src/main/res/menu/activity_main_drawer.xml, android/app/src/main/res/navigation/mobile_navigation.xml, android/app/src/main/res/values/strings.xml
Solves #318.
User now can see his/her total amount of money in a new page.
User now can deposit money to his/her account.
User now can withdraw money from his/her account.
=> Money endpoint implement in Android

android/app/src/main/java/com/papel/ui/articles/AddArticleActivity.java, android/app/src/main/java/com/papel/ui/articles/ArticlesFragment.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/activity_add_article.xml, android/app/src/main/res/values/strings.xml
Adding image to articles from mobile is implemented.
Solves #328.
=> Added image url field in "Add Article page"

android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/SearchAdapter.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/content_main.xml, android/app/src/main/res/menu/main.xml, android/app/src/main/res/values/strings.xml
Added a search icon to the toolbar. User can search for user, event and trading equipment. Clicking on an item takes user to the related page for user and trading equipment. Clicking on event doesn't do anything for now. It will be implemented later.
=> Implemented a basic search functionality

backend/helpers/alert.js, backend/helpers/errors.js, backend/jobs/jobs.js, backend/models/alert.js, backend/models/alertNotification.js, backend/routes/currency.js, backend/routes/profile.js, backend/routes/stock.js, backend/routes/user.js, backend/services/alert.js, backend/services/currency.js, backend/services/notification.js, backend/services/stock.js, backend/swagger.json
This pr contains backend endpoints to set alerts for currencies & stocks.
User can set alerts to get notified when the price/rate of the stock/currency is above/below given rate. Once the condition for an alert is met, user get a notification and the alert is deleted. Also, user can view alerts on his profile.
fixes #336
=> Implement backend endpoints for alerts for stocks & currencies

frontend/papel-frontend/src/Article/Article.js, frontend/papel-frontend/src/Article/CommentPreview.js, frontend/papel-frontend/src/Home/Home.js, frontend/papel-frontend/src/Home/StockChart2.js, frontend/papel-frontend/src/Home/USD.js, frontend/papel-frontend/src/Profile/Profile.js, frontend/papel-frontend/src/helpers/request.js
- Bug in comments on articles is fixed (see the related issue).
- Money information view, deposit&withdraw of money section implemented in profile page.
- We still have to implement a functionality to buy stocks, currencies and etc. with money.
- The charts in homepage are converted into dynamic rather than static.
------------
We still need to implement functionality on using money.
=> Article Comments, Home Page Charts & Money Section

backend/helpers/errors.js
I have merged incorrect code. I have fixed it
=> fix incorrect resolved conflict

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/data/Annotation.java, android/app/src/main/java/com/papel/data/AnnotationBody.java, android/app/src/main/java/com/papel/data/Article.java, android/app/src/main/java/com/papel/ui/articles/AnnotationListViewAdapter.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/articles/ShowAnnotationActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/activity_read_article.xml, android/app/src/main/res/layout/activity_show_annotation.xml, android/app/src/main/res/layout/annotation_comment.xml, android/app/src/main/res/layout/article_header.xml, android/app/src/main/res/values/colors.xml
=> Android annotation

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/data/Alert.java, android/app/src/main/java/com/papel/ui/profile/AlertAdapter.java, android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageAdapter.java, android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/alert_row.xml, android/app/src/main/res/values/strings.xml
=> Android alerts

backend/jobs/jobs.js, backend/models/alertNotification.js, backend/swagger.json
As requested by the android team, now the alert notifications contain currency id
=> return currency id on alert notification

backend/swagger.json
Added endpoints to sell trading equipments
=> added documentation to sell trading equipments

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/SearchAdapter.java, android/app/src/main/java/com/papel/data/Article.java, android/app/src/main/java/com/papel/data/Currency.java, android/app/src/main/java/com/papel/data/Event.java, android/app/src/main/java/com/papel/data/Stock.java, android/app/src/main/java/com/papel/data/User.java, android/app/src/main/java/com/papel/ui/investments/AddInvestmentActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/content_main.xml
Reimplemented search in mobile using backend endpoint. Solves #329.
=> Replaced search functionality with semantic search.

android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsFragment.java, android/app/src/main/res/layout/edit_comment_prompt.xml, android/app/src/main/res/menu/alert_menu.xml, android/app/src/main/res/values/strings.xml
Setting alarms is implemented. A long click on the list item on trading equipments page shows the prompt to set the alarm. Solves  #353.
=> Setting alarms functionality is implemented

android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java
Trading equipment page was not working when it is opened from search results.I fix it.
=> Fix trading equipment bug from search

backend/.env, backend/app.js, backend/models/article.js, backend/routes/recommendation.js, backend/services/article.js, backend/services/recommendation.js, backend/swagger.json
Implemented endpoints to recommend nearby users and similar articles liked by user.
=> Implement recommendation endpoints

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/data/User.java, android/app/src/main/java/com/papel/ui/investments/AddInvestmentActivity.java, android/app/src/main/java/com/papel/ui/investments/InvestmentsFragment.java
Get the default investment instance of the user. Issue: #306
=> Implemented a method to get investments of the user

backend/app.js, backend/models/alert.js, backend/services/stock.js, backend/swagger.json
As requested by the Android team, now alerts contains stock symbol
=> add stock symbol to alerts

backend/services/article.js, backend/services/recommendation.js
Now, if the text body contains non-alphanumeric characters, topics are tried to fetched again with special characters removed. Also, changed the empty response
=> fix article recommendatitions

backend/routes/event.js, backend/services/event.js
This pr implements filters for events
fixes #333
=> Implement filters for events

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/res/drawable/ic_notification.xml, android/app/src/main/res/layout/content_main.xml, android/app/src/main/res/menu/main.xml, android/app/src/main/res/values/strings.xml
I added a bell icon to the tool bar to show the notifications to the user. If the bell is clicked the notifications are showing. Later clicking the notification will dismiss the notification.
Issue #377.
=> The functionality to show notifications is implemented.

.gitignore, android/app/src/main/java/com/papel/SellButtonListener.java, android/app/src/main/java/com/papel/data/Alert.java, android/app/src/main/java/com/papel/data/Currency.java, android/app/src/main/java/com/papel/data/Investment.java, android/app/src/main/java/com/papel/data/Stock.java, android/app/src/main/java/com/papel/data/UserInvestments.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/investments/AddInvestmentActivity.java, android/app/src/main/java/com/papel/ui/investments/InvestmentListViewAdapter.java, android/app/src/main/java/com/papel/ui/investments/InvestmentsFragment.java, android/app/src/main/java/com/papel/ui/profile/AlertAdapter.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
=> Android investments

frontend/papel-frontend/package-lock.json, frontend/papel-frontend/package.json, frontend/papel-frontend/src/App.css, frontend/papel-frontend/src/App.js, frontend/papel-frontend/src/Article/Annotation.js, frontend/papel-frontend/src/Article/Article.js, frontend/papel-frontend/src/Profile/FileUpload.js, frontend/papel-frontend/src/Profile/Portfolio.js, frontend/papel-frontend/src/Profile/Profile.js, frontend/papel-frontend/src/Trading/TradingEquipment.js, frontend/papel-frontend/src/config.js
Image annotations are not communicating with backend yet
=> Image Annotations, Alert Notifications, Profile Picture Upload Fix

android/app/src/main/java/com/papel/ui/investments/AddInvestmentActivity.java, android/app/src/main/java/com/papel/ui/investments/InvestmentsFragment.java
Fix update bug in investment list after adding investment
=> Fix update bug in investment list after adding investment

android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/NotificationAdapter.java, android/app/src/main/java/com/papel/data/PapelNotification.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java, android/app/src/main/res/layout/content_main.xml, android/app/src/main/res/values/strings.xml
Created notification data structure and list adapter for showing notifications. Also made some style changes. No notifications message is showing when user has no notifications. 
Issue: #377
=> Notification structure is changed.

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/MainActivity.java, android/app/src/main/java/com/papel/data/Article.java, android/app/src/main/java/com/papel/ui/recommendations/NearbyUserAdapter.java, android/app/src/main/java/com/papel/ui/recommendations/NearbyUserFragment.java, android/app/src/main/java/com/papel/ui/recommendations/RecommendationFragment.java, android/app/src/main/java/com/papel/ui/recommendations/RecommendationSubpageAdapter.java, android/app/src/main/java/com/papel/ui/recommendations/RecommendedArticleAdapter.java, android/app/src/main/java/com/papel/ui/recommendations/RecommendedArticleFragment.java, android/app/src/main/res/layout/fragment_nearby_user.xml, android/app/src/main/res/layout/fragment_recommendation.xml, android/app/src/main/res/layout/fragment_recommended_article.xml, android/app/src/main/res/layout/nearby_user_row.xml, android/app/src/main/res/layout/recommended_article_row.xml, android/app/src/main/res/menu/activity_main_drawer.xml, android/app/src/main/res/navigation/mobile_navigation.xml, android/app/src/main/res/values/strings.xml
I added recommendation screen.
=> Android recommendation

android/app/src/main/java/com/papel/Constants.java, android/app/src/main/java/com/papel/data/AnnotationBody.java, android/app/src/main/java/com/papel/ui/articles/AnnotationListViewAdapter.java, android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java, android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
Now, we are showing name and surname of the user who made comment or annotation.
=> Android annotation name fix

backend/services/recommendation.js
If the recommended article has more than one tag matching with the randomly selected article, we were recommending the same article more than once
=> return only the unique article recommendations

frontend/papel-frontend/src/Currency/Currencies.js, frontend/papel-frontend/src/Currency/CurrencyTable.js, frontend/papel-frontend/src/Currency/Prediction.js, frontend/papel-frontend/src/EconEvent/EconEvent.js, frontend/papel-frontend/src/EconEvent/EconEventPreview.js
I deleted uncessary console.log s
=> Currencies page 

backend/services/recommendation.js
We were also returning the user that does the request in the nearby users. With this fix, this issue is resolved.
=> do not return the user in the nearby users
